const promptCategories = {
    music: [
    {
        id: 1,
        title: "Song Lyrics Generator",
        content: "Write original song lyrics for a [genre] song about [theme/topic]. Include:\n\nStructure Requirements:\n- Verse 1 (8-16 lines): Set the scene and introduce the story/emotion\n- Pre-Chorus (4-8 lines): Build tension and anticipation\n- Chorus (6-12 lines): Main hook with memorable melody line, repeat key phrase\n- Verse 2 (8-16 lines): Develop the story, add new perspective or details\n- Pre-Chorus (repeat or slight variation)\n- Chorus (repeat)\n- Bridge (6-10 lines): Contrasting melody/perspective, emotional climax\n- Final Chorus (with ad-libs or variations)\n\nContent Specifications:\n- Target audience: [specify age group and demographics]\n- Emotional arc: [describe the journey from start to finish]\n- Rhyme scheme: [ABAB, AABB, or genre-appropriate pattern]\n- Syllable count consistency for singability\n- Include internal rhymes and alliteration where appropriate\n- Avoid cliché phrases unless subverting them cleverly\n- Include specific imagery and sensory details\n- Ensure radio-friendly language (or specify explicit content warnings)\n\nGenre-Specific Elements:\n- Pop: Focus on universal themes, simple language, repetitive hooks\n- Rock: Powerful imagery, rebellion themes, strong rhythmic emphasis\n- Country: Storytelling, rural imagery, traditional values, narrative arc\n- Hip-Hop: Wordplay, cultural references, rhythm and flow emphasis\n- Folk: Social commentary, traditional storytelling, acoustic feel\n\nProvide the complete lyrics with [Verse], [Chorus], [Bridge] labels and include notes on suggested vocal emphasis or delivery style."
    },
    {
        id: 2,
        title: "Music Theory Lesson",
        content: "Create a comprehensive music theory lesson on [topic] for [beginner/intermediate/advanced] students. Structure the lesson as follows:\n\nLesson Overview (2-3 minutes):\n- Learning objectives (3-5 specific, measurable goals)\n- Prerequisites knowledge students should have\n- Materials needed (instruments, apps, worksheets)\n- Estimated completion time\n\nCore Content (15-25 minutes):\n- Clear definition of key terms with pronunciation guides\n- Step-by-step concept breakdown with visual aids descriptions\n- Musical notation examples (describe what to write on staff paper)\n- Audio examples with specific songs/pieces to reference\n- Common misconceptions to address explicitly\n- Memory devices, mnemonics, or mental models\n\nInteractive Elements:\n- 3-5 hands-on exercises progressing from simple to complex\n- Partner or group activities if applicable\n- Technology integration (apps, online tools, software)\n- Real-time assessment questions\n\nPractical Application (10-15 minutes):\n- How this concept appears in popular songs (provide 3-5 specific examples)\n- Composition/improvisation exercises using the concept\n- Connection to students' favorite genres\n- Performance opportunities to demonstrate understanding\n\nAssessment & Extension:\n- Quick formative assessment (exit ticket questions)\n- Practice assignments for home\n- Additional resources for students who want to dive deeper\n- Accommodation suggestions for different learning styles\n- Next lesson preview and how concepts connect"
    },
    {
        id: 3,
        title: "Advanced Playlist Curator",
        content: "Curate a meticulously crafted playlist of [number] songs for [specific occasion/mood/activity]. Provide comprehensive details:\n\nPlaylist Foundation:\n- Total runtime: [specify exact duration needed]\n- Target audience demographics and musical preferences\n- Setting/context where playlist will be used\n- Desired emotional journey from start to finish\n- Energy arc (BPM progression and intensity mapping)\n\nSong Selection Criteria:\n- Genre blend ratios (e.g., 40% indie rock, 30% electronic, 30% pop)\n- Release date range (specify era focus)\n- Popularity balance (mainstream hits vs. deep cuts vs. discoveries)\n- Lyrical content appropriateness and themes\n- Audio quality and mastering consistency\n\nDetailed Track Listing:\nFor each song provide:\n- Track number, artist, song title, album, release year\n- Duration and BPM\n- Key and tempo\n- Why it fits the playlist's purpose (2-3 sentences)\n- Emotional/energy contribution to the flow\n- Notable production elements or unique characteristics\n- Suggested crossfade/transition time to next track\n\nFlow Architecture:\n- Opening strategy (how to capture attention)\n- Act 1, 2, 3 breakdown with distinct purposes\n- Climax placement and energy management\n- Cool-down strategy and finale selection\n- Transition notes between contrasting songs\n\nAlternative Versions:\n- 3-5 substitute tracks for different moods or censorship needs\n- Shorter version (50% length) with essential tracks only\n- Extended version with 5-10 additional complementary songs\n- Seasonal or time-sensitive variations"
    },
    {
        id: 4,
        title: "Kids Music & Poems Generator",
        content: "Create a delightful children's musical poem or song with these specifications:\n\nAge Group: [Toddlers (1-3) | Preschool (3-5) | Early Elementary (6-8)]\n\nEducational Objectives:\n- [Choose 1-3: Alphabet learning | Counting | Animal sounds | Colors | Manners | Nature awareness]\n- [Optional: Social-emotional skill development]\n\nMusical Style:\n- [Nursery rhyme | Action song | Lullaby | Circle game | Fingerplay | March]\n- [Specify if acoustic/folk or upbeat/pop style]\n\nStructural Requirements:\n1. Verse 1 (4-8 lines): Introduce main concept with simple vocabulary\n2. Chorus (4-6 lines): Memorable, repetitive hook with physical movement cues\n3. Verse 2 (4-8 lines): Expand on concept with new examples\n4. Bridge (2-4 lines): Interactive element (call-and-response or clapping rhythm)\n5. Final Chorus (with variation): Include child participation instructions\n\nContent Guidelines:\n- Use concrete, familiar objects (animals, household items, nature)\n- Include 2-3 onomatopoeic words (moo, splash, boom)\n- Repeat 3-5 key vocabulary words\n- Limit to 1-2 syllable words (for younger ages)\n- Incorporate simple rhyming (AABB or ABAB patterns)\n- Add movement/action instructions (clap, jump, spin)\n\nMusical Elements to Specify:\n- Tempo (bouncy 120bpm vs. slow 80bpm)\n- Suggested simple melody shape (ascending/descending)\n- Recommended percussion instruments (tambourine, shaker, drum)\n- Vocal dynamics (whispered verses vs. loud chorus)\n\nExample Output Format:\n\"The Happy Counting Walk\" (Preschool)\n(Upbeat acoustic guitar, 110bpm)\n\n[Verse 1]\nLet's take a walk down the lane, (walk in place)\nCounting things that aren't the same!\n1 red flower waving hi, (hold up 1 finger)\n2 blue birds that fly up high! (flap arms)\n\n[Chorus]\nCount with me, 1-2-3! (clap on each number)\nSo many pretty things to see!\nCount with me, up we go! (reach up high)\nHow many next? Let's know! (hand to ear)\n\n[Verse 2]\n3 green frogs jump in the pool, (jump 3 times)\n4 yellow ducks so nice and cool...\n\nExtensions:\n1. Create a simplified version for toddlers\n2. Suggest accompanying hand motions/dance\n3. Include sign language for key words\n4. Provide coloring page ideas matching the song\n5. Recommend storybooks with similar themes"
    },
    {
        id: 5,
        title: "Animal Adventure Song Generator",
        content: "Create an interactive animal-themed song for kids ages 2-6 with these elements:\n\nStructure:\n- Intro (4 lines): Set the scene (jungle, farm, ocean) with sound effects\n- Verse 1 (4-6 lines): Introduce 1st animal + movement (e.g., 'Hop like a bunny!')\n- Chorus (4 lines): Repeatable action phrase ('Animals dance, stomp, and play!')\n- Verse 2 (4-6 lines): Introduce 2nd animal + new motion\n- Bridge (2-4 lines): Silly interaction (e.g., 'What if a cow said meow?')\n- Ending (2 lines): Wind-down transition (e.g., 'Now we tiptoe home... shh!')\n\nRequired Elements:\n- 3+ animal sounds (moo, roar, hiss)\n- 2-3 action verbs (jump, slither, flap)\n- Simple AABB or ABCB rhyme scheme\n- Call-and-response section ('Can you roar like a lion? *ROAR!*')\n- Props suggestion (stuffed animals, scarves)\n\nExample:\n🐘 *Verse:* \"An elephant stomps with big heavy feet (stomp feet),\\nTrumpets loud for a snack to eat! (hand to mouth like a trunk)\"\n🎵 *Chorus:* \"Animal parade, come along!\\nMove your body and sing this song!\""
    },
    {
    id: 6,
    title: "Bedtime Lullaby & Poem Generator",
    content: "Compose a soothing lullaby or rhyming poem for bedtime with:\n\nStructure:\n- Opening (2 lines): Gentle invitation ('Stars are blinking, eyes grow heavy...')\n- Verse 1 (4 lines): Calming imagery (moon, blankets, sleepy animals)\n- Refrain (2 lines): Repeating whisper phrase ('Dream soft, little one')\n- Verse 2 (4 lines): Progressive relaxation cues ('Your toes are warm, your hands at rest...')\n- Closing (1 line): Signature send-off ('Goodnight to the whole wide nest')\n\nKey Features:\n- Soft consonant sounds (m, s, l, sh)\n- 3/4 or 6/8 time signature suggestion\n- Diminishing energy (start mid-tempo, end slow)\n- Optional parent cues ('Rock baby gently during refrain')\n- Sensory details (warmth, weight, safety)\n\nExample:\n🌙 *Verse:* \"The moon’s a pearl in the velvet sky,\\nBlankets nestle you, cozy and tight.\"\n🦉 *Refrain:* \"Hooo says the owl, soft and low,\\nTime to drift where dream winds blow.\""
},
{
    id: 7,
    title: "Learning Rhyme Generator",
    content: "Generate an educational rhyme/song teaching basics (letters, numbers, or social skills):\n\nStructure:\n- Hook (2 lines): Catchy question/exclamation ('A is for what? Let’s see!')\n- Teaching Verse (6-8 lines): Sequential learning (alphabet, counting 1-10, please/thank you)\n- Action Break (2 lines): Physical reinforcement ('Clap for B! Jump for 3!')\n- Review Chorus (4 lines): Cumulative repetition ('Now we know our ABCs!')\n\nCustomization:\n- For Letters: Include phonics ('B says /b/ like bouncing ball')\n- For Numbers: Add objects ('5 bright buttons on a coat')\n- For Manners: Scenario-based ('When you want a turn, say ___?')\n\nExample:\n *Verse:* \"3 little ducks go quack, quack, quack,\\nWaddle forward, then scoot right back!\\nAdd 2 more—how many now?\\nLet’s count them all: 1, 2, 3, 4, 5... WOW!\"\n✨ *Action:* \"Flap your wings and say '5 ducks please!'\\n(Use fingers to count while singing)\""
}
        
        
    ],
    video: [
    {
        id: 4,
        title: "Professional Video Script Writer",
        content: "Write a compelling, production-ready video script for a [duration] minute [explainer/promotional/educational/entertainment] video about [specific topic]. Format as a professional shooting script:\n\nPre-Production Elements:\n- Target audience analysis (demographics, viewing context, attention span)\n- Primary objective and call-to-action strategy\n- Tone and brand voice guidelines\n- Platform optimization (YouTube/TikTok/Instagram/LinkedIn/Website)\n- Budget considerations and production complexity level\n\nScript Structure:\n\nHOOK (0:00-0:10):\n- Visual: [Describe opening shot in detail]\n- Audio: [Background music style, sound effects]\n- Voiceover/Dialogue: [Exact words with emphasis marks]\n- Text Overlay: [Any graphics, titles, or captions]\n- Objective: Capture attention and prevent scroll-away\n\nINTRODUCTION (0:10-0:30):\n- Introduce problem/topic with relatable scenario\n- Establish credibility and value proposition\n- Preview what viewers will learn/gain\n\nMAIN CONTENT (organized in 30-60 second segments):\n- Segment 1: [Core point with supporting visuals]\n- Segment 2: [Development with examples/case studies]\n- Segment 3: [Solution/instruction with step-by-step breakdown]\n- Include engagement retention elements every 30 seconds\n\nCONCLUSION & CTA (final 15-30 seconds):\n- Summarize key takeaways\n- Strong, specific call-to-action\n- Next steps for viewer engagement\n\nProduction Notes:\n- Camera angles and shot types for each scene\n- Lighting requirements and mood specifications\n- Props, wardrobe, and location needs\n- Post-production effects and editing style\n- Accessibility considerations (captions, audio descriptions)\n- A/B testing variations for key elements"
    },
    {
        id: 5,
        title: "Educational Video Series Architect",
        content: "Develop a comprehensive educational video series on [subject] for [grade level/skill level]. Create a complete curriculum framework:\n\nSeries Overview:\n- Total episodes: [number] with [duration] each\n- Learning progression from foundational to advanced concepts\n- Alignment with educational standards (Common Core, state standards, etc.)\n- Assessment integration and progress tracking methods\n- Prerequisite knowledge and skill requirements\n\nEpisode Breakdown:\n\nFor each episode provide:\n- Episode title and 2-sentence description\n- Specific learning objectives (measurable outcomes)\n- Key vocabulary terms introduced\n- Essential questions that drive inquiry\n- Materials/resources students need\n- Estimated homework/practice time\n\nPedagogical Framework:\n- Visual learning strategies (animations, infographics, demonstrations)\n- Auditory elements (narration style, music, sound effects)\n- Kinesthetic activities that can be done while watching\n- Multiple intelligence approaches (logical, visual, musical, etc.)\n- Differentiation strategies for various learning needs\n- Cultural responsiveness and inclusivity considerations\n\nEngagement & Retention Strategies:\n- Interactive elements (pause-and-reflect prompts, polls)\n- Storytelling techniques and narrative threads\n- Real-world connections and current event tie-ins\n- Student choice and agency opportunities\n- Gamification elements (badges, progress tracking)\n- Social learning components (discussion prompts, peer sharing)\n\nAssessment & Feedback:\n- Formative assessment checkpoints throughout each episode\n- Summative assessment options (quizzes, projects, portfolios)\n- Self-reflection and metacognitive prompts\n- Peer assessment opportunities\n- Teacher dashboard and analytics recommendations\n\nTechnical Specifications:\n- Production timeline and resource requirements\n- Accessibility features (closed captions, audio descriptions, multiple languages)\n- Device compatibility and bandwidth considerations\n- Integration with learning management systems\n- Offline viewing and download capabilities"
    },
    {
        id: 6,
        title: "YouTube Channel Growth Strategy",
        content: "Create a comprehensive YouTube channel strategy for [niche/topic] targeting [specific audience]. Develop a complete roadmap:\n\nChannel Foundation:\n- Channel name options with availability check strategy\n- Value proposition and unique selling point (what makes you different)\n- Target audience avatar (demographics, psychographics, viewing habits)\n- Competitive analysis of top 5 channels in niche\n- Brand personality and tone guidelines\n- Visual identity elements (color scheme, fonts, logo concepts)\n\nContent Strategy:\n\nPillar Content Categories (3-5 main types):\n- Category 1: [Description, upload frequency, example titles]\n- Category 2: [Description, upload frequency, example titles]\n- Category 3: [Description, upload frequency, example titles]\n\nFirst 90 Days Content Calendar:\n- Week-by-week upload schedule with specific video topics\n- Seasonal/trending content opportunities\n- Series and recurring content formats\n- Collaboration and guest appearance plans\n- Community posts and engagement content\n\nSEO & Discovery Optimization:\n- Keyword research strategy and tools to use\n- Title formulas for different content types\n- Thumbnail design principles and A/B testing plan\n- Description templates and optimization techniques\n- Tag strategy and hashtag research\n- End screen and card optimization\n\nCommunity Building:\n- Comment engagement strategy and response templates\n- Community tab content ideas and posting schedule\n- Live streaming schedule and format ideas\n- Cross-platform promotion strategy (Instagram, TikTok, Twitter)\n- Email list building and newsletter integration\n- Merchandise and product development timeline\n\nAnalytics & Growth Tracking:\n- Key performance indicators (KPIs) to monitor\n- Monthly review process and adjustment strategies\n- Audience retention analysis and improvement tactics\n- Revenue tracking and monetization milestones\n- A/B testing protocols for optimization\n\nMonetization Roadmap:\n- AdSense qualification timeline and requirements\n- Sponsorship rate cards and pitch templates\n- Affiliate marketing integration strategies\n- Product/service development opportunities\n- Patreon or membership program planning"
    }],
    text: [
    {
        id: 7,
        title: "Comprehensive Assessment Generator",
        content: "Generate a complete assessment package for [subject/topic] at [grade level]. Create multiple question types and comprehensive evaluation materials:\n\nAssessment Overview:\n- Total questions: [number] across multiple formats\n- Estimated completion time\n- Point distribution and weighting\n- Difficulty progression (25% easy, 50% medium, 25% challenging)\n- Learning objectives alignment\n- Accommodation options for diverse learners\n\nMultiple Choice Questions (10-15 questions):\n\nFor each question provide:\n- Clear, concise stem without unnecessary information\n- Four plausible distractors based on common misconceptions\n- One definitively correct answer marked with *\n- Detailed explanation including why correct answer is right and why others are wrong\n- Bloom's taxonomy level (Knowledge, Comprehension, Application, Analysis, Synthesis, Evaluation)\n- Estimated difficulty level and time requirement\n\nAdditional Question Types:\n- True/False with justification (5 questions)\n- Short answer/fill-in-blank (5 questions)\n- Essay questions with rubrics (2-3 questions)\n- Matching or sequencing activities\n- Problem-solving scenarios with multiple steps\n\nAssessment Support Materials:\n- Student instruction sheet with clear expectations\n- Scoring rubric for subjective questions\n- Answer key with detailed explanations\n- Common error analysis and remediation suggestions\n- Extension activities for early finishers\n- Alternative assessment options for different learning styles\n\nQuality Assurance:\n- Bias review checklist\n- Reading level appropriateness verification\n- Cultural sensitivity considerations\n- Time allocation testing recommendations\n- Peer review suggestions for improvement"
    },
    {
        id: 8,
        title: "Creative Writing Workshop Designer",
        content: "Design a complete creative writing experience for [grade level] students. Create an immersive, multi-faceted writing workshop:\n\nCore Writing Prompt:\n- Compelling scenario with rich sensory details\n- Character archetypes with distinct motivations and backgrounds\n- Setting with historical/cultural significance and atmospheric elements\n- Central conflict with multiple resolution possibilities\n- Thematic elements that connect to students' lives and experiences\n- Genre flexibility (realistic fiction, fantasy, sci-fi, historical fiction, etc.)\n\nPre-Writing Activities:\n- Character development worksheets with personality traits, backstory, goals\n- Setting research and world-building exercises\n- Plot outline templates (three-act structure, hero's journey, etc.)\n- Conflict mapping and tension escalation planning\n- Voice and point-of-view exploration activities\n- Sensory detail brainstorming and observation exercises\n\nWriting Process Support:\n- Daily writing targets and milestone checkpoints\n- Peer review protocols and feedback forms\n- Self-editing checklists for different writing elements\n- Teacher conferencing schedule and focus areas\n- Technology tools and resources (writing apps, research databases)\n- Inspiration sources (mentor texts, multimedia stimuli)\n\nLiterary Elements Integration:\n- Specific techniques to practice (dialogue, description, pacing, foreshadowing)\n- Genre conventions and reader expectations\n- Point of view experimentation opportunities\n- Theme development through symbolic elements\n- Style and voice development exercises\n- Grammar and mechanics in context\n\nAssessment & Sharing:\n- Holistic writing rubric with specific criteria\n- Portfolio development and reflection components\n- Publishing and sharing opportunities (class anthology, reading aloud, digital platform)\n- Celebration and recognition strategies\n- Extension opportunities for motivated writers\n- Differentiation for various skill levels and interests"
    },
    {
        id: 9,
        title: "Conversion-Focused Marketing Copy Generator",
        content: "Write high-converting marketing copy for [product/service] targeting [specific audience segment]. Create a complete conversion-optimized campaign:\n\nAudience Analysis:\n- Primary demographics (age, income, location, profession)\n- Psychographics (values, interests, lifestyle, pain points)\n- Customer journey stage (awareness, consideration, decision, retention)\n- Previous purchasing behavior and decision-making factors\n- Preferred communication channels and content consumption habits\n- Objections and hesitations to address\n\nCore Messaging Framework:\n\nHeadlines (5 variations):\n- Benefit-focused headline emphasizing primary value proposition\n- Curiosity-driven headline that creates intrigue\n- Problem-solution headline addressing specific pain point\n- Social proof headline featuring testimonials or statistics\n- Urgency/scarcity headline motivating immediate action\n\nBody Copy Structure:\n- Hook: Attention-grabbing opening that connects emotionally\n- Problem: Detailed description of audience pain points and frustrations\n- Agitation: Amplify the consequences of not solving the problem\n- Solution: Introduce your product/service as the ideal solution\n- Benefits: Focus on outcomes and transformations, not just features\n- Social Proof: Testimonials, reviews, case studies, statistics\n- Objection Handling: Address common concerns and hesitations\n- Risk Reversal: Guarantees, free trials, money-back promises\n\nCall-to-Action Optimization:\n- Primary CTA with action-oriented, benefit-focused language\n- Secondary CTA for less committed prospects\n- Urgency elements (limited time, exclusive offers, countdown timers)\n- Friction reduction (simple forms, guest checkout, free shipping)\n- Multiple CTA placements throughout the copy\n\nPlatform-Specific Adaptations:\n- Email marketing version with subject line variations\n- Social media versions (Facebook, Instagram, LinkedIn, Twitter)\n- Landing page long-form version\n- Google Ads headlines and descriptions\n- Video script adaptation for YouTube or social video\n\nTesting & Optimization Plan:\n- A/B testing elements to experiment with\n- Metrics to track (click-through rates, conversion rates, cost per acquisition)\n- Timeline for testing and iteration cycles\n- Seasonal adjustments and campaign refresh strategies"
    }],
    picture: [
    {
        id: 10,
        title: "Comprehensive Visual Arts Project",
        content: "Design a complete visual arts project for [grade level] students exploring [theme/concept]. Create a multi-week artistic journey:\n\nProject Overview:\n- Duration: [number] weeks with [number] class periods per week\n- Essential question driving artistic inquiry\n- Cross-curricular connections (history, science, literature, math)\n- Cultural and historical context research component\n- Contemporary artist study and inspiration gathering\n\nArtistic Learning Objectives:\n- Technical skills development (specific techniques and media)\n- Creative problem-solving and experimentation goals\n- Art criticism and analysis capabilities\n- Cultural awareness and artistic appreciation\n- Personal expression and voice development\n- Collaboration and peer feedback skills\n\nMaterials & Resources:\n\nBasic Supplies (required):\n- Primary materials with specific brand/quality recommendations\n- Tools and equipment needed\n- Safety equipment and studio setup requirements\n- Budget-friendly alternatives and DIY options\n- Recycled/upcycled material possibilities\n\nAdvanced Materials (optional extensions):\n- Premium supplies for students ready for challenges\n- Digital tools and software options\n- Specialized equipment for advanced techniques\n\nWeek-by-Week Progression:\n\nWeek 1-2: Research & Planning\n- Artist study and technique exploration\n- Preliminary sketches and concept development\n- Material experimentation and testing\n- Peer discussion and feedback sessions\n\nWeek 3-4: Production Phase 1\n- Foundation building and basic composition\n- Technical skill practice and refinement\n- Problem-solving and adaptation strategies\n- Individual conferencing and guidance\n\nWeek 5-6: Production Phase 2\n- Detail development and refinement\n- Color theory and design principle application\n- Peer collaboration and constructive criticism\n- Documentation of process and progress\n\nWeek 7: Completion & Reflection\n- Final touches and finishing techniques\n- Artist statement writing and self-reflection\n- Presentation preparation and display setup\n- Celebration and sharing with community\n\nAssessment Framework:\n- Process portfolio documentation requirements\n- Technical skill rubric with specific criteria\n- Creative thinking and risk-taking evaluation\n- Effort and engagement measurement\n- Peer feedback and collaboration assessment\n- Self-reflection and growth documentation\n\nDifferentiation Strategies:\n- Modifications for students with special needs\n- Extensions for advanced or gifted students\n- Multiple entry points for different skill levels\n- Choice in materials, techniques, or subject matter\n- Flexible timelines and alternative assessment options"
    },
    {
        id: 11,
        title: "Photography Mastery Challenge",
        content: "Create an intensive photography challenge focusing on [technique/theme] for [beginner/intermediate/advanced] photographers. Design a transformative learning experience:\n\nChallenge Framework:\n- Duration: [timeframe] with daily or weekly assignments\n- Skill progression from foundational to mastery level\n- Equipment requirements with budget-conscious alternatives\n- Community engagement and peer learning components\n- Portfolio development and curation goals\n\nTechnical Curriculum:\n\nCamera Settings Mastery:\n- Aperture control and depth of field manipulation\n- Shutter speed for motion capture and creative blur\n- ISO management for various lighting conditions\n- Manual mode confidence building\n- Exposure triangle mastery exercises\n- Metering modes and exposure compensation\n\nComposition Excellence:\n- Rule of thirds and advanced compositional techniques\n- Leading lines and visual flow creation\n- Symmetry, patterns, and geometric elements\n- Foreground, middle ground, background relationship\n- Color theory application in photography\n- Negative space and minimalist approaches\n\nDaily Challenge Structure:\n\nDay 1-7: Foundation Week\n- Daily prompt with specific technical focus\n- Shot requirements (minimum number, variety)\n- Technical parameters to practice\n- Composition goals and creative constraints\n- Self-assessment questions and reflection prompts\n- Peer sharing and feedback protocols\n\nEquipment Recommendations:\n\nEssential Gear:\n- Camera body options (DSLR, mirrorless, smartphone)\n- Lens recommendations for different budgets\n- Tripod selection and stability techniques\n- Lighting equipment (natural vs. artificial)\n\nMobile Photography Track:\n- Smartphone camera optimization techniques\n- Third-party app recommendations and tutorials\n- Mobile editing workflow and best practices\n- Accessory recommendations (lenses, stabilizers)\n\nPost-Processing Integration:\n- RAW vs. JPEG workflow decisions\n- Lightroom/Photoshop basic editing techniques\n- Color grading and mood enhancement\n- Batch processing and organization systems\n- Export settings for different platforms\n\nPortfolio Development:\n- Image selection and curation criteria\n- Storytelling through photographic series\n- Presentation formats (print, digital, social media)\n- Artist statement and project description writing\n- Exhibition and sharing opportunities\n\nCommunity & Feedback:\n- Daily hashtag strategy for social sharing\n- Peer critique guidelines and constructive feedback\n- Expert review sessions and mentorship opportunities\n- Online gallery creation and maintenance\n- Networking and collaboration possibilities"
    },
    {
        id: 12,
        title: "Professional Infographic Design System",
        content: "Plan and design a comprehensive infographic about [specific topic] for [target audience]. Create a complete visual communication strategy:\n\nContent Strategy & Research:\n- Primary message and key takeaways (3-5 main points)\n- Supporting data sources and credibility verification\n- Audience analysis (knowledge level, interests, viewing context)\n- Competitor analysis of similar infographics\n- Content hierarchy and information prioritization\n- Fact-checking and source attribution requirements\n\nData Visualization Planning:\n\nStatistical Elements:\n- Chart types selection (bar, pie, line, scatter, heat map)\n- Data simplification and rounding strategies\n- Comparison techniques (before/after, versus competitors)\n- Trend visualization and time-series representation\n- Percentage breakdowns and proportion displays\n\nVisual Storytelling Structure:\n- Introduction hook and context setting\n- Problem identification and scope definition\n- Solution presentation and benefit highlighting\n- Supporting evidence and credibility building\n- Call-to-action and next steps guidance\n\nDesign Specifications:\n\nLayout & Composition:\n- Dimensions and format (vertical, horizontal, square)\n- Grid system and alignment principles\n- White space utilization and breathing room\n- Visual flow and reading pattern optimization\n- Modular design for social media adaptation\n\nColor Psychology & Branding:\n- Primary color palette (3-5 colors maximum)\n- Color meaning and emotional associations\n- Accessibility considerations (contrast ratios, colorblind-friendly)\n- Brand consistency and recognition elements\n- Cultural color considerations for global audiences\n\nTypography Hierarchy:\n- Header font selection and sizing\n- Body text legibility and readability\n- Caption and data label formatting\n- Font pairing and contrast creation\n- Mobile responsiveness and scalability\n\nVisual Elements:\n\nIconography:\n- Icon style consistency (outline, filled, duotone)\n- Custom icon creation vs. stock selection\n- Icon sizing and spacing standards\n- Metaphorical representation accuracy\n\nIllustrations & Graphics:\n- Illustration style guide and consistency\n- Chart and graph design standards\n- Photo selection and treatment guidelines\n- Custom graphic element creation\n\nProduction & Distribution:\n- File format optimization (PDF, PNG, SVG)\n- Print vs. digital resolution requirements\n- Social media format variations\n- Interactive element possibilities\n- Accessibility features (alt text, screen reader compatibility)\n- Analytics tracking and performance measurement\n\nQuality Assurance:\n- Proofreading and fact-checking protocols\n- Design consistency review checklist\n- User testing and feedback incorporation\n- Mobile and device compatibility testing\n- Loading time optimization strategies"
    }],
    webapp: [
    {
        id: 13,
        title: "Interactive Web Application Builder",
        content: "Create a fully functional web application for [specific purpose/industry]. Build a complete single-page application with modern features:\n\nApplication Specifications:\n- Primary function and user goals\n- Target users (demographics, technical proficiency, device usage)\n- Core features and functionality requirements\n- Performance benchmarks (load time, responsiveness)\n- Browser compatibility requirements\n- Accessibility standards compliance (WCAG guidelines)\n\nTechnical Architecture:\n\nFrontend Structure:\n- HTML5 semantic structure and accessibility features\n- CSS3 with modern layout techniques (Flexbox, Grid)\n- Vanilla JavaScript with ES6+ features\n- Responsive design for mobile-first approach\n- Progressive Web App capabilities\n- Local storage for data persistence\n\nCore Features to Implement:\n- User interface with intuitive navigation\n- Form handling with validation and error messages\n- Dynamic content generation and DOM manipulation\n- API integration for external data sources\n- Real-time updates and live data synchronization\n- Search and filter functionality\n- Drag-and-drop interactions\n- Modal dialogs and interactive elements\n\nUser Experience Design:\n\nInterface Design:\n- Clean, modern visual design with consistent styling\n- Color scheme and typography that enhances usability\n- Loading states and micro-interactions for engagement\n- Error handling with helpful user feedback\n- Keyboard navigation and screen reader support\n\nFunctionality Requirements:\n- Data input and validation with real-time feedback\n- CRUD operations (Create, Read, Update, Delete)\n- Export/import capabilities (JSON, CSV formats)\n- Print-friendly layouts and PDF generation\n- Offline functionality with service workers\n\nCode Structure & Best Practices:\n- Modular JavaScript with clear separation of concerns\n- CSS organization with BEM methodology or similar\n- Code comments and documentation\n- Error handling and debugging strategies\n- Performance optimization techniques\n- Security considerations and input sanitization\n\nTesting & Deployment:\n- Cross-browser testing checklist\n- Mobile responsiveness verification\n- Performance testing and optimization\n- User acceptance testing scenarios\n- Deployment preparation and hosting considerations\n\nProvide complete, production-ready code with detailed comments explaining functionality and implementation decisions."
    },
    {
        id: 14,
        title: "Educational Web Tool Creator",
        content: "Develop an interactive educational web tool for [subject/skill] targeting [grade level/age group]. Create an engaging learning experience with gamification elements:\n\nEducational Framework:\n- Learning objectives aligned with curriculum standards\n- Pedagogical approach (constructivist, inquiry-based, etc.)\n- Assessment integration and progress tracking\n- Differentiation strategies for various learning styles\n- Teacher dashboard and classroom management features\n\nInteractive Learning Features:\n\nCore Functionality:\n- Interactive lessons with multimedia integration\n- Self-paced learning modules with branching scenarios\n- Immediate feedback and adaptive responses\n- Progress tracking with visual indicators\n- Achievement system with badges and rewards\n- Collaborative features for peer learning\n\nGamification Elements:\n- Point system and experience levels\n- Achievement badges for milestones and mastery\n- Leaderboards with privacy considerations\n- Challenge modes and timed activities\n- Virtual rewards and customizable avatars\n- Story-based learning adventures\n\nAssessment & Analytics:\n- Formative assessment tools integrated throughout\n- Summative assessment options with automatic grading\n- Learning analytics dashboard for teachers\n- Student progress reports and portfolio development\n- Parent communication and home connection features\n\nTechnical Implementation:\n\nFrontend Technologies:\n- HTML5 Canvas for interactive graphics and animations\n- CSS3 animations and transitions for engagement\n- JavaScript for dynamic content and user interactions\n- Web APIs for multimedia and device integration\n- Responsive design for various devices and screen sizes\n\nData Management:\n- Local storage for offline capability\n- JSON-based data structure for content management\n- Import/export functionality for teacher resources\n- Backup and sync capabilities across devices\n\nAccessibility & Inclusion:\n- Screen reader compatibility and ARIA labels\n- Keyboard navigation for all interactive elements\n- Multiple language support and translation features\n- Adjustable text size and high contrast options\n- Cognitive load considerations and clean interface design\n\nContent Management:\n- Modular lesson structure for easy updates\n- Media integration (images, audio, video)\n- Interactive simulations and virtual experiments\n- Real-world problem-solving scenarios\n- Cultural relevance and diverse representation\n\nDeliver a complete educational web application with detailed implementation notes, usage instructions, and extension possibilities for different subjects or grade levels."
    },
    {
        id: 15,
        title: "Business Dashboard Generator",
        content: "Build a comprehensive business dashboard web application for [industry/business type]. Create a data-driven interface for decision-making and performance monitoring:\n\nDashboard Requirements:\n- Key Performance Indicators (KPIs) relevant to the industry\n- Real-time data visualization and updates\n- Historical trend analysis and forecasting\n- Multi-user access with role-based permissions\n- Mobile-responsive design for on-the-go access\n- Export capabilities for reports and presentations\n\nData Visualization Components:\n\nChart Types & Metrics:\n- Revenue and financial performance charts (line, bar, area)\n- Customer analytics and demographic breakdowns (pie, donut)\n- Sales pipeline and conversion funnels\n- Geographic data representation with interactive maps\n- Performance comparison tables and scorecards\n- Real-time activity feeds and notifications\n\nInteractive Features:\n- Date range selectors and time period filtering\n- Drill-down capabilities for detailed analysis\n- Custom dashboard layouts and widget arrangement\n- Alert systems for threshold monitoring\n- Bookmark and save favorite views\n- Collaboration tools for sharing insights\n\nTechnical Architecture:\n\nFrontend Implementation:\n- Responsive grid layout system for dashboard widgets\n- Chart.js or D3.js integration for data visualization\n- Dynamic data loading with loading states\n- Real-time updates using WebSocket simulation\n- Local storage for user preferences and settings\n- Print and PDF export functionality\n\nData Management:\n- Sample dataset generation for realistic testing\n- JSON-based data structure for flexibility\n- Data aggregation and calculation functions\n- Filtering and search capabilities\n- Data validation and error handling\n\nUser Experience Design:\n\nInterface Design:\n- Professional business-appropriate styling\n- Intuitive navigation and information hierarchy\n- Consistent color coding for data categories\n- Hover effects and interactive feedback\n- Loading animations and smooth transitions\n\nFunctionality Features:\n- User profile management and customization\n- Dashboard templates for different roles\n- Notification center and alert management\n- Help system and guided tours for new users\n- Keyboard shortcuts for power users\n\nBusiness Intelligence Features:\n- Automated report generation and scheduling\n- Goal setting and progress tracking\n- Benchmark comparisons and industry standards\n- Predictive analytics and trend forecasting\n- Action item tracking and task management\n\nSecurity & Performance:\n- Input validation and sanitization\n- Secure data handling practices\n- Performance optimization for large datasets\n- Caching strategies for improved load times\n- Error logging and debugging capabilities\n\nProvide a complete, professional"
    }]
}

export default promptCategories